# BASIC

In [1]:
import numpy as np #importing numpy as np (np-alias)

In [2]:
np.__version__ #checking version

'1.26.4'

In [3]:
arr = np.array([1,2,3,4]) #creating array by passing list

In [4]:
print(arr) #we can print like this or simply we can write veriable name like(arr)

[1 2 3 4]


In [5]:
type(arr) #checking type

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4])

## slicing and indexing

In [7]:
arr[0]

1

In [8]:
arr[-1] # gives last element

4

In [9]:
arr[0:2] # 0-1 index elements are printed 

array([1, 2])

## Basic Attributes

In [10]:
arr.ndim #check diemntion

1

In [11]:
arr.size #checks size

4

In [12]:
arr.shape #checking shape

(4,)

In [13]:
arr.dtype # checking data type

dtype('int32')

## Dimension of arrays

In [ ]:
# 1D
# 2D
# 3D
# ND

### 1d array

In [14]:
#1d array
# 1-D array or 1-Dimensional array is  like a simple list of items .
# It requires only one index to access the individual element


In [15]:
one_d = np.array([1,2,3,4,5])

In [16]:
one_d.ndim

1

In [17]:
one_d[4] ##one index are required to access an individual element

5

In [18]:
one_d.shape

(5,)

### 2d array

In [19]:
#2d array
# 2D array is like a list of lists. 
# It requires two index to access the individual element 

In [20]:
two_d = np.array([[1,2,3],[3,4,5]])

In [21]:
two_d.ndim

2

In [22]:
two_d

array([[1, 2, 3],
       [3, 4, 5]])

In [23]:
two_d[1][1] ##two index are required to access an individual element

4

In [24]:
two_d.shape

(2, 3)

### 3d array

In [25]:
#3d array
# 3D array is like a list of lists of lists . 
# It requires three index to access the individual element 

In [26]:
three_d = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])

In [27]:
three_d

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
three_d.ndim

3

In [29]:
three_d[1][1][0] #three index are required to access an individual element

6

In [30]:
three_d.shape

(2, 2, 2)

# Data Types

In [31]:
arr = np.array([1,2,3,4])

In [32]:
arr

array([1, 2, 3, 4])

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr = np.array([1,2,3,4])

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr.itemsize # how many bytes of memory is used by per elemnt (in this case 4 byte of memory per element)

4

In [37]:
arr1 = np.array([1,2,3,4],dtype = 'int8') #changing datatype to int8

In [38]:
arr1.dtype

dtype('int8')

In [39]:
arr1.itemsize 

1

In [131]:
# arr2 = np.array([1,2,3,128],dtype = 'int8') #error 

# Array creation


#### 1. Conversion from other Python structures (i.e. lists and tuples)

In [43]:
l1 = [1,2,3,4] # simple list
arr = np.array(l1) #making array from l1 list

In [44]:
arr

array([1, 2, 3, 4])

In [45]:
type(arr)

numpy.ndarray

In [46]:
t1 = (1,2,3,4) #simple tuple
arr1 = np.array(t1) #making array from t1 tuple

In [47]:
arr1

array([1, 2, 3, 4])

In [48]:
type(arr1)

numpy.ndarray

#### 2.Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

#### arange

In [51]:
arr2 = np.arange(10) #gives array in range of 0-9

In [52]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### ones

In [54]:
arr3 = np.ones((3,2)) #passing shape (gives array with all one )

In [55]:
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
# zeros

In [57]:
arr4 = np.zeros((4,2)) #passing shape(4,2)  (gives array with all zeros )

In [58]:
arr4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### 3. Replicating, joining, or mutating existing arrays

#### Replicating (duplicating)

In [61]:
arr = np.array([1,2,3,4])

In [62]:
replicate_array = np.tile(arr,5) #tile function is used to replicate

In [63]:
replicate_array

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

#### joining

In [65]:
arr1 =  np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])


In [66]:
join_array = np.concatenate((arr1,arr2)) #joining two arrays using concatination

In [67]:
join_array

array([1, 2, 3, 4, 5, 6, 7, 8])

#### mutating (reshaping)

In [69]:
arr1 =  np.array([1,2,3,4])

In [70]:
arr = np.reshape(arr1,(4,1)) #reshaping arry to shape(4,1)

In [71]:
arr

array([[1],
       [2],
       [3],
       [4]])

#### Use of special library functions (e.g., random)

In [73]:
rand_arr = np.random.rand(5,2) # generates random numbers in a given shape over a range of (0-1)

In [74]:
rand_arr

array([[0.80300017, 0.8260954 ],
       [0.01787403, 0.07245705],
       [0.35593035, 0.05000173],
       [0.13325254, 0.61350966],
       [0.38845336, 0.06497704]])

In [75]:
rand_int = np.random.randint(10,20,size=(2,3)) # generates random integer within a specified range (10-20 with size (2,3))

In [76]:
rand_int

array([[18, 13, 11],
       [19, 13, 15]])

# Functions and Operations

#### Functions

In [79]:
arr = np.arange(10).reshape(5,2)

In [80]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [81]:
arr.min() # finds minimum element

0

In [82]:
arr.max() # finds maximum element

9

In [83]:
arr.sum() # sum all the elements

45

In [84]:
np.sqrt(arr) # finds sqrt of given array

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])

#### Operation

In [85]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [86]:
arr1 = np.arange(10,20).reshape(5,2)

In [87]:
arr1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [88]:
arr+arr1 # adding two arrays

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [89]:
arr*arr1 # mult two arrays

array([[  0,  11],
       [ 24,  39],
       [ 56,  75],
       [ 96, 119],
       [144, 171]])

In [90]:
arr/arr1 # div two arrays

array([[0.        , 0.09090909],
       [0.16666667, 0.23076923],
       [0.28571429, 0.33333333],
       [0.375     , 0.41176471],
       [0.44444444, 0.47368421]])

In [91]:
# l1 = [1,2,3]
# l2=[4,5,6]

In [92]:
# l1*l2  # error

# Axis

In [93]:
# axis 0 - column
# axis 1 - row

In [94]:
auta_array = np.arange(12).reshape(4,3)

In [95]:
auta_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
auta_array.sum()

66

In [97]:
auta_array.sum(axis = 0)

array([18, 22, 26])

In [98]:
auta_array.sum(axis = 1)

array([ 3, 12, 21, 30])

# Iteration

In [99]:
# Repetitive execution

In [100]:
arr = np.arange(12).reshape(3,4)

In [101]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
for row in arr:
    for cell in row:
        print(cell)
  
    

0
1
2
3
4
5
6
7
8
9
10
11


In [132]:
for cell in arr.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


 #### nditer

In [105]:
for x in np.nditer(arr,order = 'f'):
    print(x)


0
4
8
1
5
9
2
6
10
3
7
11


In [106]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
arr1 = np.arange(1,9,3).reshape(3,1)

In [108]:
arr1

array([[1],
       [4],
       [7]])

In [109]:
for x,y in np.nditer((arr,arr1)):
    print(x,y)
    


0 1
1 1
2 1
3 1
4 4
5 4
6 4
7 4
8 7
9 7
10 7
11 7


# Read and write files

In [111]:
arr = np.arange(12).reshape(3,4)

In [112]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Text (reading and writing text file)

In [114]:
np.savetxt('test1.txt',arr)

In [115]:
a = np.loadtxt('test1.txt')

In [116]:
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### Binay file (reading and writing binary file)

In [118]:
np.save('test2.npy',arr)

In [119]:
b = np.load('test2.npy')

In [120]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Zip file (reading and writing Zip file)

In [122]:
a = np.arange(12).reshape(3,4)

In [123]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
b = np.arange(10).reshape(5,2)

In [125]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [126]:
np.savez('test3.npz',x = a,y = b)

In [127]:
data = np.load('test3.npz')

In [128]:
data['x']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
data['y']

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])